# Generated by Django 5.1 on 2024-09-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_useractionlog_action_type'),
        ('properties', '0014_alter_property_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='properties.property'),
            preserve_default=False,
        ),
    ]
