# Generated by Django 5.1 on 2024-09-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_useractionlog_action_type_and_more'),
        ('properties', '0015_alter_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='properties.property'),
        ),
    ]
