# Generated by Django 5.1 on 2024-08-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agent',
            new_name='agente',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bathrooms',
            new_name='baños',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='habitaciones',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='titulo',
        ),
    ]
