# Generated by Django 5.1 on 2024-08-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_agent_property_agente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='role',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='phone',
            new_name='telefono',
        ),
    ]
