# Generated by Django 5.1 on 2024-08-30 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_role_agent_cargo_rename_name_agent_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='cargo',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='agente',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='baños',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='habitaciones',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
