# Generated by Django 5.1 on 2024-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_nombre_agent_name_rename_telefono_agent_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='common_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contributions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('office', 'Oficina'), ('commercial', 'Comercial'), ('plot', 'Parcela'), ('parking', 'Estacionamiento'), ('warehouse', 'Bodega'), ('land', 'Terreno')], default='house', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
