# Generated by Django 5.1 on 2024-08-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_area_remove_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='comuna',
            field=models.CharField(choices=[('santiago', 'Santiago'), ('las_condes', 'Las Condes'), ('providencia', 'Providencia'), ('puente_alto', 'Puente Alto'), ('la_florida', 'La Florida'), ('maipu', 'Maipú'), ('san_bernardo', 'San Bernardo'), ('quilicura', 'Quilicura'), ('pudahuel', 'Pudahuel'), ('renca', 'Renca'), ('independencia', 'Independencia'), ('recoleta', 'Recoleta'), ('conchali', 'Conchalí'), ('huechuraba', 'Huechuraba'), ('colina', 'Colina'), ('lampa', 'Lampa'), ('tiltil', 'Tiltil'), ('lo_barnechea', 'Lo Barnechea'), ('vitacura', 'Vitacura'), ('la_reina', 'La Reina'), ('penalolen', 'Peñalolén'), ('macul', 'Macul'), ('nunoa', 'Ñuñoa'), ('san_joaquin', 'San Joaquín'), ('la_granja', 'La Granja'), ('el_bosque', 'El Bosque'), ('san_ramón', 'San Ramón'), ('la_pintana', 'La Pintana'), ('lo_espejo', 'Lo Espejo'), ('cerrillos', 'Cerrillos'), ('cerro_navia', 'Cerro Navia'), ('quinta_normal', 'Quinta Normal'), ('lo_prado', 'Lo Prado'), ('padre_hurtado', 'Padre Hurtado'), ('el_monte', 'El Monte'), ('isla_de_maipo', 'Isla de Maipo'), ('melipilla', 'Melipilla'), ('curacavi', 'Curacaví'), ('maria_pinto', 'María Pinto'), ('san_pedro', 'San Pedro'), ('buin', 'Buin'), ('paine', 'Paine'), ('talagante', 'Talagante'), ('peñaflor', 'Peñaflor'), ('calera_de_tango', 'Calera de Tango')], default='santiago', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('arica_parinacota', 'Arica y Parinacota'), ('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('ohiggins', "Libertador Gral. Bernardo O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('rios', 'Los Ríos'), ('lagos', 'Los Lagos'), ('aysen', 'Aysén del Gral. Carlos Ibáñez del Campo'), ('magallanes', 'Magallanes y de la Antártica Chilena'), ('metropolitana', 'Región Metropolitana de Santiago')], default='metropolitana', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('office', 'Oficina'), ('commercial', 'Comercial'), ('plot', 'Parcela'), ('parking', 'Estacionamiento'), ('warehouse', 'Bodega'), ('land', 'Terreno')], default='house', max_length=20),
        ),
    ]
