# Generated by Django 5.1 on 2024-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_bathrooms_property_baños_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='imagenes',
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('metropolitana', 'Región Metropolitana de Santiago')], default='metropolitana', max_length=20),
        ),
    ]
