# Generated by Django 5.1 on 2024-08-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_image_property_imagenes_alter_property_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='titulo',
            new_name='title',
        ),
    ]
