# Generated by Django 5.1 on 2024-08-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='imagenes',
        ),
    ]
