# Generated by Django 5.1 on 2024-09-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
