# Generated by Django 5.1 on 2024-09-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], default='venta', max_length=8),
        ),
    ]
