# Generated by Django 5.1 on 2024-09-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_profiles/'),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_renta_uf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_venta_uf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='comuna',
            field=models.CharField(choices=[('santiago', 'Santiago'), ('las_condes', 'Las Condes'), ('providencia', 'Providencia')], default='santiago', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('comercial', 'Comercial'), ('parcela', 'Parcela'), ('estacionamiento', 'Estacionamiento'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='casa', max_length=20),
        ),
    ]
