# Generated by Django 5.1 on 2024-09-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_agent_profile_image_property_precio_renta_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('metropolitana', 'Región Metropolitana de Santiago')], default='metropolitana', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('comercial', 'Comercial'), ('parcela', 'Parcela'), ('estacionamiento', 'Estacionamiento'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='casa', max_length=50),
        ),
    ]
