# Generated by Django 5.1.1 on 2024-10-11 18:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_agent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='precio_renta_uf',
        ),
        migrations.RemoveField(
            model_name='property',
            name='precio_venta_uf',
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
