# Generated by Django 5.1.1 on 2024-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_property_precio_renta_uf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ambientes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='expensas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='moneda',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='superficie_cubierta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='superficie_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
