# Generated by Django 5.1.1 on 2024-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_ambientes_property_expensas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('arriendo temporal', 'Arriendo Temporal')], default='venta', max_length=50),
        ),
    ]
