# Generated by Django 5.1.1 on 2024-10-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_property_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('arriendo_temporal', 'Arriendo Temporal')], default='venta', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tipo_propiedad',
            field=models.CharField(choices=[('departamento', 'Departamentos'), ('casa', 'Casas'), ('oficina', 'Oficinas'), ('parcela', 'Parcelas'), ('local', 'Locales'), ('terreno', 'Terrenos'), ('sitio', 'Sitios'), ('bodega', 'Bodegas'), ('industrial', 'Industriales'), ('agricola', 'Agrícolas'), ('otros_inmuebles', 'Otros Inmuebles'), ('estacionamiento', 'Estacionamientos'), ('loteo', 'Loteos'), ('lotes_de_cementerio', 'Lotes de Cementerio')], default='casa', max_length=50),
        ),
    ]
