# Generated by Django 5.1.1 on 2024-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_alter_property_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mercadolibre_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
