# Generated by Django 5.1.1 on 2024-10-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_property_mercadolibre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ubicacion_referencia',
            field=models.CharField(blank=True, help_text='Ubicación de referencia para la propiedad', max_length=255, null=True),
        ),
    ]
