# Generated by Django 5.1.1 on 2024-11-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_ufvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='moneda',
        ),
        migrations.AddField(
            model_name='property',
            name='precio_renta_en_uf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_venta_en_uf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='valor_uf_al_momento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
