# Generated by Django 5.1.1 on 2024-11-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_remove_property_moneda_property_precio_renta_en_uf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='precio_renta_en_uf',
        ),
        migrations.RemoveField(
            model_name='property',
            name='precio_venta_en_uf',
        ),
        migrations.AddField(
            model_name='property',
            name='moneda_precio',
            field=models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', help_text='Selecciona si el precio principal está en CLP o UF', max_length=3),
        ),
    ]
