# Generated by Django 5.1.1 on 2024-11-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_remove_property_precio_renta_en_uf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Indica si la propiedad está visible en el sitio web', verbose_name='Publicada'),
        ),
    ]
