# Generated by Django 5.1.1 on 2024-11-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_property_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='precio_renta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
