# Generated by Django 5.1.1 on 2024-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_alter_property_precio_renta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único de la propiedad', max_length=100, null=True, unique=True),
        ),
    ]
